logging:
  level:
    org.springframework: WARN
---
spring:
  profiles:
    active: testing
---
spring:
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/in2lab?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  config:
    activate:
      on-profile: local
---
spring:
  jpa:
    database: H2
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  config:
    activate:
      on-profile: testing

